# Font
font_family      FiraCode Nerd Font
font_size        12.0

# Monokai Pro Octagon Color Scheme
foreground       #eaf2f1
background       #282a3a

# Cursor
cursor           #ff657a
cursor_text_color #282a3a

# Selection
selection_foreground #282a3a
selection_background #ff657a

# URL
url_color        #9cd1bb

# Black
color0   #282a3a
color8   #696d77

# Red
color1   #ff657a
color9   #ff657a

# Green
color2   #bad761
color10  #bad761

# Yellow
color3   #ffd76d
color11  #ffd76d

# Blue
color4   #9cd1bb
color12  #9cd1bb

# Magenta
color5   #c39ac9
color13  #c39ac9

# Cyan
color6   #9cd1bb
color14  #9cd1bb

# White
color7   #eaf2f1
color15  #eaf2f1

# Window
background_opacity 0.85
window_padding_width 8

# Tab bar
tab_bar_style powerline
active_tab_foreground   #282a3a
active_tab_background   #ff657a
inactive_tab_foreground #b2b9bd
inactive_tab_background #1e1f2b

# Misc
confirm_os_window_close 0
